Added latmem package to buildroot
chipsalliance/omnixtend pull request #3
Opened 2019-12-17 20:06 UTC by tudang-wdc

2019-12-18 01:03 UTC, atishp04 requested changes
Otherwise, looks good.

2019-12-18 01:03 UTC, atishp04 commented on software/patches/buildroot/latmem.patch
> +@@ -1871,6 +1871,7 @@ menu "Miscellaneous"
It should be put under benchmark not Miscellaneous.

2019-12-18 01:03 UTC, atishp04 commented on software/patches/buildroot/latmem.patch
> ++CC=riscv64-linux-
I don't think you need to explicitly export PATH or CC for individual package. Buildroot should take care of that.
It also may not work on other machines as toolchain prefix or toolchain install path may be different.

2019-12-18 18:50 UTC, tudang-wdc commented
Hi Atish,

I added some changes to your request. Please merge if the changes look good.

2019-12-19 01:19 UTC, atishp04 approved these changes
FYI: You can squash any fixes that address the comments and just update the branch.

I am merging this PR. Please update the rootfs file with latmem benchmark as a separate PR.

2019-12-19 01:19 UTC, merged